In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import Module
from Module import Linear_Regression

In [6]:
df = pd.read_csv('data.csv')
df

,carat,cut,color,clarity,depth,table,x,y,z,price
0,0.544971,Ideal,E,SI1,63.911017,52.575829,5.447452,4.053076,3.701485,3.558
1,2.073682,Premium,J,SI1,67.642925,57.660288,6.266665,7.661507,6.177051,24.738
2,0.606198,Premium,G,VS1,55.617310,60.388787,6.800151,5.096966,3.480326,3.630
3,0.695397,Premium,G,SI2,60.587811,71.325721,5.366931,6.616767,4.454435,4.218
4,0.282651,Ideal,E,VVS2,68.970056,54.372123,4.920104,4.409408,4.361358,1.578
...,...,...,...,...,...,...,...,...,...,...
11995,0.251768,Premium,E,VS1,69.674513,52.790228,5.657402,5.832983,3.386799,1.628
11996,1.729415,Premium,H,SI1,56.191121,48.024573,6.725585,8.624433,4.822269,15.508
11997,2.252697,Very Good,I,SI2,64.007494,63.641838,8.510526,9.108384,3.674364,20.018
11998,0.139030,Very Good,D,VS2,64.885328,55.383459,2.799799,2.281538,2.419920,0.746
11999,0.320988,Ideal,G,IF,68.921055,62.357899,4.970371,7.428551,3.648548,1.660

In [7]:
df.drop(columns=['cut','color','clarity']).corr() # No need to consider depth,table in determination of price

          carat     depth     table         x         y         z     price
carat  1.000000  0.006378  0.063873  0.714913  0.712074  0.542008  0.901114
depth  0.006378  1.000000 -0.028407 -0.016920 -0.004879  0.013562 -0.001962
table  0.063873 -0.028407  1.000000  0.067479  0.052183  0.039767  0.041725
x      0.714913 -0.016920  0.067479  1.000000  0.562207  0.415738  0.664324
y      0.712074 -0.004879  0.052183  0.562207  1.000000  0.419319  0.663095
z      0.542008  0.013562  0.039767  0.415738  0.419319  1.000000  0.499839
price  0.901114 -0.001962  0.041725  0.664324  0.663095  0.499839  1.000000

In [8]:
df = pd.get_dummies(df.drop(columns=['depth','table'])).astype(float)
df

,carat,x,y,z,price,cut_Fair,cut_Good,cut_Ideal,cut_Premium,cut_Very Good,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0.544971,5.447452,4.053076,3.701485,3.558,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2.073682,6.266665,7.661507,6.177051,24.738,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.606198,6.800151,5.096966,3.480326,3.630,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.695397,5.366931,6.616767,4.454435,4.218,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.282651,4.920104,4.409408,4.361358,1.578,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,0.251768,5.657402,5.832983,3.386799,1.628,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
11996,1.729415,6.725585,8.624433,4.822269,15.508,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11997,2.252697,8.510526,9.108384,3.674364,20.018,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
11998,0.139030,2.799799,2.281538,2.419920,0.746,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11999,0.320988,4.970371,7.428551,3.648548,1.660,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

# Normalization

In [5]:
Norm_df = Module.Normalize(df,df.columns)
df_train, df_test = Module.train_test_split(Norm_df, test_size=0.2, random_state=42)

# Training Model

In [6]:
X_train = df_train.drop(columns=['price'])
Y_train = df_train['price']
model = Linear_Regression(0.01,1000)
model.fit(X_train,Y_train)

# Prediction

In [7]:
X_test = df_test.drop(columns=['price'])
Y_test = df_test['price']
result = model.predict(X_test)
R2 = Module.R2(result,Y_test)
print('Accuracy of Model is '+str(R2*100)+' %')

Accuracy of Model is 99.9808741778886 %